- README.md
- package.json
WordPress is spelt with a [capital_P_dangit](https://developer.wordpress.org/reference/functions/capital_p_dangit/)
> capital_P_dangit

- CHANGELOG.md
- index.js
- package.json
Added rule: `declaration-colon-newline-after` with option `always-multi-line`
> Added rule: `declaration-colon-newline-after`

- CHANGELOG.md
- __tests__/index.js
- index.js
> Remove `media-query-parentheses-space-inside` rule

- package.json
> Add peerDependencies section to package.json and declare stylelint dependency version

- .travis.yml
- appveyor.yml
Set Travis-CI and AppVeyor to only build the master branch (preventing duplicate builds on PRs).
Also only clone the last 10 commits.
> Only build master

- package.json
• https://github.com/sindresorhus/eslint-plugin-ava
• https://www.npmjs.com/package/eslint-plugin-ava
> Add ESLint rules for AVA

- CHANGELOG.md
- index.js
> Add `comment-empty-line-before` rule

- CHANGELOG.md
- __tests__/properties.js
- index.js
> feat: Add `value-keyword-case` rule.

- CHANGELOG.md
- index.js
> feat: Add `selector-attribute-quotes` rule

- CHANGELOG.md
- README.md
- __tests__/values.js
- index.js
> feat: Add `font-weight-notation` rule.

- CHANGELOG.md
- README.md
- __tests__/commenting.js
- index.js
> feat: Add `max-line-length` rule.

- CHANGELOG.md
- __tests__/properties.js
- index.js
> feat: Add `property-no-unknown` rule.

- CHANGELOG.md
- __tests__/media-queries.js
- index.js
> feat: Add `at-rule-no-unknown` rule.

- CHANGELOG.md
- __tests__/selectors.js
- index.js
> feat: Add `selector-class-pattern` and  `selector-id-pattern` rules.

- README.md
- __tests__/scss.js
- package.json
- scss.js
> feat: Add SCSS preset config

- package.json
> chore: Update remark and remark plugin packages

- CHANGELOG.md
- __tests__/scss-invalid.scss
- __tests__/scss-valid.scss
- __tests__/scss.js
- scss.js
> test: Update `stylelint-scss` plugin @if/@else tests.

- __tests__/functions-invalid.css
- __tests__/functions-valid.css
- __tests__/functions.js
- index.js
> fix: Ignore proprietary `DXImageTransform.Microsoft` MS filters

- __tests__/commenting.js
- __tests__/functions.js
- __tests__/index.js
- __tests__/media-queries.js
- __tests__/properties.js
- __tests__/scss.js
- __tests__/selectors-scss.js
- __tests__/selectors.js
- __tests__/structure.js
- __tests__/values.js
- __tests__/vendor-prefixes.js
- package.json
- scss.js
> Update eslint to the latest 4.1.x version

- package-lock.json
- package.json
> chore(package): update stylelint-find-rules to version 1.0.1

- .editorconfig
- .eslintrc.json
- package.json
See https://core.trac.wordpress.org/ticket/43075 / https://core.trac.wordpress.org/changeset/42460/
> Update `*.json` indentation per WordPress Coding Standards

- package.json
https://marionebl.github.io/commitlint/
> chore: add commitlint

- .travis.yml
- appveyor.yml
> Update to node 10 in .travis.yml

- package.json
> chore(package): update husky to version 1.1.2

- __tests__/__snapshots__/media-queries.test.js.snap
- __tests__/__snapshots__/properties.test.js.snap
- __tests__/__snapshots__/scss.test.js.snap
- __tests__/__snapshots__/structure.test.js.snap
- package.json
> chore(package): update stylelint to version 10.0.1

- package.json
> Greenkeeper/husky 2.2.0

- __tests__/__snapshots__/scss.test.js.snap
- package.json
> chore(package): update husky to version 3.0.1

- .travis.yml
- package.json
Add Windows jobs to Travis CCI
> ci: add Windows to Travis CI

- package.json
> chore(package): update @wordpress/scripts to version 6.1.1

- package.json
> chore(package): update @wordpress/scripts to version 8.0.1

- package.json
> chore(package): update @wordpress/scripts to version 10.0.0
